# Generated by Django 5.2.6 on 2025-09-14 01:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='sent', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='requires_payment_method', help_text='Payment status based on Stripe payment intent status', max_length=32)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.businessowner')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('category', models.CharField(choices=[('USER', 'User'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('TRANSACTION', 'Transaction'), ('DATABASE', 'Database'), ('API', 'API'), ('HEALTH', 'Health'), ('SYSTEM', 'System'), ('ERROR', 'Error')], max_length=20)),
                ('message_template', models.TextField()),
                ('formatted_message', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'level'], name='core_logeve_timesta_295f1d_idx'), models.Index(fields=['category', 'timestamp'], name='core_logeve_categor_60223e_idx'), models.Index(fields=['user_id', 'timestamp'], name='core_logeve_user_id_2f02d4_idx'), models.Index(fields=['level', 'timestamp'], name='core_logeve_level_22f257_idx')],
            },
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='requires_payment_method', max_length=32)),
                ('payment_method_type', models.CharField(default='card', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_created_at', models.DateTimeField()),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=500)),
                ('stripe_metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to='core.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
