# Generated by Django 5.2.6 on 2025-09-10 01:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_businessowner_user_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('overdue', 'Overdue')], default='sent', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.businessowner')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
    ]
