# Generated by Django 5.2.6 on 2025-09-11 01:06

from django.db import migrations, models


def populate_invoice_numbers(apps, schema_editor):
    Invoice = apps.get_model('core', 'Invoice')
    
    for i, invoice in enumerate(Invoice.objects.all(), 1):
        year = invoice.issued_at.year
        month = invoice.issued_at.month
        
        # Generate a unique number for this invoice
        invoice.number = f"INV-{year}{month:02d}-{i:04d}"
        invoice.save()


def reverse_populate_invoice_numbers(apps, schema_editor):
    Invoice = apps.get_model('core', 'Invoice')
    Invoice.objects.all().update(number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoice_number_delete_payment'),
    ]

    operations = [
        migrations.RunPython(
            populate_invoice_numbers,
            reverse_populate_invoice_numbers,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
