# Generated by Django 5.2.6 on 2025-09-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transaction_transaction_type_stripepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='requires_payment_method', help_text='Payment status based on Stripe payment intent status', max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='sent', max_length=16),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='requires_payment_method', max_length=32),
        ),
    ]
