# Generated by Django 5.2.6 on 2025-09-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_invoice_payment_status_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
