# Generated by Django 5.2.6 on 2025-09-13 18:23

from django.db import migrations


def convert_draft_to_sent(apps, schema_editor):
    Invoice = apps.get_model('core', 'Invoice')
    # Convert any existing draft invoices to sent status
    Invoice.objects.filter(status='draft').update(status='sent')


def reverse_convert_draft_to_sent(apps, schema_editor):
    # This is a no-op since we can't reliably reverse this operation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250913_1600'),
    ]

    operations = [
        migrations.RunPython(convert_draft_to_sent, reverse_convert_draft_to_sent),
    ]
