# Generated by Django 5.2.6 on 2025-09-13 19:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_draft_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('category', models.CharField(choices=[('USER', 'User'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('TRANSACTION', 'Transaction'), ('DATABASE', 'Database'), ('API', 'API'), ('HEALTH', 'Health'), ('SYSTEM', 'System'), ('ERROR', 'Error')], max_length=20)),
                ('message_template', models.TextField()),
                ('formatted_message', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'level'], name='core_logeve_timesta_295f1d_idx'), models.Index(fields=['category', 'timestamp'], name='core_logeve_categor_60223e_idx'), models.Index(fields=['user_id', 'timestamp'], name='core_logeve_user_id_2f02d4_idx'), models.Index(fields=['level', 'timestamp'], name='core_logeve_level_22f257_idx')],
            },
        ),
    ]
