
API_PREFIX = "api/"
ADMIN_PREFIX = "admin/"
HEALTH_PREFIX = "health/"
HEALTH_DB_PATH = "health/db/"

INVOICES_PATH = "invoices/"
TRANSACTIONS_PATH = "transactions/"
PAYMENTS_PATH = "payments/"

BUSINESS_OWNERS_PATH = "business-owners/"
BUSINESS_OWNERS_DETAIL_PATH = "business-owners/<uuid:company_name>/"
BUSINESS_OWNERS_INVOICES_PATH = "business-owners/<uuid:company_name>/invoices/"
BUSINESS_OWNERS_TRANSACTIONS_PATH = "business-owners/<uuid:business_owner_id>/transactions/"

CUSTOMERS_PATH = "customers/"
CUSTOMERS_DETAIL_PATH = "customers/<uuid:customer_id>/"
CUSTOMERS_INVOICES_PATH = "customers/<uuid:customer_id>/invoices/"
CUSTOMERS_TRANSACTIONS_PATH = "customers/<uuid:customer_id>/transactions/"

INVOICES_ROOT_PATH = ""
INVOICE_DETAIL_PATH = "<uuid:invoice_id>/"
INVOICE_TRANSACTIONS_PATH = "<uuid:invoice_id>/transactions/"
INVOICE_CREATE_PAYMENT_INTENT_PATH = "<uuid:invoice_id>/create-payment-intent/"

TRANSACTIONS_ROOT_PATH = ""
TRANSACTION_DETAIL_PATH = "<uuid:transaction_id>/"

PAYMENTS_ROOT_PATH = ""
PAYMENT_DETAIL_PATH = "<uuid:stripe_payment_id>/"
PAYMENT_REFUND_PATH = "<uuid:stripe_payment_id>/refund/"

WEBHOOKS_PATH = "webhooks/"
STRIPE_WEBHOOK_PATH = "webhooks/stripe/"

HEALTH_CHECK_NAME = "health_check"
HEALTH_CHECK_DB_NAME = "health_check_db"
BUSINESS_OWNERS_NAME = "business_owners"
BUSINESS_OWNER_DETAIL_NAME = "business_owner_detail"
BUSINESS_OWNER_INVOICES_NAME = "business_owner_invoices"
BUSINESS_OWNER_TRANSACTIONS_NAME = "business_owner_transactions"
CUSTOMERS_NAME = "customers"
CUSTOMER_DETAIL_NAME = "customer_detail"
CUSTOMER_INVOICES_NAME = "customer_invoices"
CUSTOMER_TRANSACTIONS_NAME = "customer_transactions"
INVOICES_NAME = "invoices"
INVOICE_DETAIL_NAME = "invoice_detail"
INVOICE_TRANSACTIONS_NAME = "invoice_transactions"
CREATE_PAYMENT_INTENT_NAME = "create_payment_intent"
PAYMENT_HISTORY_NAME = "payment_history"
PAYMENT_DETAIL_NAME = "payment_detail"
STRIPE_WEBHOOK_NAME = "stripe_webhook"
REFUND_PAYMENT_NAME = "refund_payment"

CORE_APP_NAME = "core"
USERS_APP_NAME = "users"
INVOICES_APP_NAME = "invoices"
TRANSACTIONS_APP_NAME = "transactions"
PAYMENTS_APP_NAME = "payments"