name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Django Tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
        DEBUG: 'False'
        SECRET_KEY: 'test-secret-key-for-ci-only'
        STRIPE_API_SECRET_KEY: 'sk_test_fake_key_for_testing'
        STRIPE_WEBHOOK_SECRET: 'whsec_test_webhook_secret'
      run: |
        python manage.py check
        python manage.py migrate
        python manage.py test
